### ISSUE TITLE
Dependencies non installées par setup.py

### ISSUE THREAD

**Issue by stella-bourdin** [yrobink/CDSK#1]
Bonjour, 

Je viens d'installer le package en tapant `pip install --user --editable .` depuis le dossier python/ où se trouve le fichier setup.py. Cependant, cela n'a pas installé les dépendances que je vois dans le "requires", et surtout SDFC. (Que j'essaie actuellement d'installer depuis le git sans succès)

Cordialement, 
Stella

**Comment by yrobink** [comment]
Bonjour Stella,

Le lien vers SDFC est donné dans le README de CDSK: https://github.com/yrobink/SDFC . 

Bien cordialement,

Yoann
